--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlexPads/CommandSpy  and https://witherhosting.com/
main: CommandSpy/TinyPixelDevz/AlexPads
branches:
- master
projects:
  CommandSpy:
    path: ""
...
